[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "grok-mem"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
run-demo = "python src/main/python/fcf_demo_runner.py"
java-test = "mvn -B test"
java-build = "mvn -B clean package"
java-lint = "mvn -B checkstyle:check"
java-format = "mvn -B spotless:apply"
java-docs = "mvn -B javadoc:javadoc"
java-micro-test = "./run-micro-tests.sh"
java-all-tests = "./run-all-tests.sh"
java-test-temurin23 = { cmd = "mvn -B test", env = { JAVA_HOME = "/Library/Java/JavaVirtualMachines/temurin-23.jdk/Contents/Home" } }
java-all-tests-temurin23 = { cmd = "./run-all-tests.sh", env = { JAVA_HOME = "/Library/Java/JavaVirtualMachines/temurin-23.jdk/Contents/Home" } }

[dependencies]
python = ">=3.8"
typing-extensions = "*"
maven = "*"
checkstyle = "*"
google-java-format = "*"
