[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "grok-mem"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
run-demo = "python src/main/python/fcf_demo_runner.py"

[dependencies]
python = ">=3.8"
typing-extensions = "*"
